version: '3'
services:
  nginx:
    image: nginx
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - /etc/nginx:/etc/nginx
     - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
     - www
  www:
    build: ./www/
  kanboard:
    image: kanboard/kanboard
    volumes:
     - /etc/kanboard/data:/var/www/app/data
     - /etc/kanboard/plugins:/var/www/app/plugins
